services:
  bend:
    build:
      context: ./bend
      dockerfile: Dockerfile
    container_name: django-backend
    ports:
      - "3000:80"
    environment:
      - DEBUG=1  # Set to 0 for production
      - DJANGO_ALLOWED_HOSTS=localhost  # Add your domain in production
      - REDIS_BROKER_URL=redis://redis:6379/0  # Redis connection URL
      - DATABASE_URL=postgres://test-user:password@postgres-db:5432/core
      - ITEM_FILE_PATH=/app/res/items.json
    depends_on:
      - db
    networks:
      - safa
    env_file: ./bend/.env

  fend:
    build:
      context: ./fend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "8080:80"
    networks:
      - safa

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: core
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - safa
  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - safa
    ports:
      - "6379:6379"

volumes:
  postgres_data:
networks:
  safa: