# Generated by Django 5.0.1 on 2024-11-21 16:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        help_text="A user-friendly representation of the address.",
                        max_length=1024,
                    ),
                ),
                ("street_no", models.CharField(max_length=10)),
                ("street", models.CharField(max_length=512)),
                ("apt_no", models.CharField(blank=True, max_length=10, null=True)),
                ("city", models.CharField(max_length=512)),
                ("state", models.CharField(max_length=512)),
                (
                    "zip_code",
                    models.CharField(
                        blank=True,
                        help_text="Optional ZIP or postal code.",
                        max_length=512,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "ordering": ["city", "state"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("password", models.CharField(max_length=512)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "primary_address",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user's primary address, if specified.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_users",
                        to="app.address",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                help_text="The user associated with this address.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="app.user",
            ),
        ),
        migrations.CreateModel(
            name="Return",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("annual_income", models.FloatField(blank=True, null=True)),
                ("taxable_income", models.FloatField(blank=True, null=True)),
                ("taxes_owed", models.FloatField(blank=True, null=True)),
                ("taxes_refunded", models.FloatField(blank=True, null=True)),
                ("attended_school", models.BooleanField(default=False)),
                ("owned_home", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="app.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "year")},
            },
        ),
    ]
